### ISSUE TITLE
Unsaved annotations are not correctly modified

### ISSUE THREAD

**Issue by Janchorizo** [providedh/collaborative-platform#112]
The following existing unsaved uncertainty annotation is correctly modified:
```
"{"ana":"https://providedh.ehum.psnc.pl/api/projects/2/taxonomy/#imprecision","locus":"value","degree":null,"cert":"medium","resp":"#annotator-2","match":null,"target":"#utensil-1","xml:id":"certainty-2","assertedValue":"oven","desc":"","saved":false,"deleted":false}"
```

The following request is sent in order to change the asserted value:
```
{"method":"modify","payload":[{"element_type":"certainty","method":"PUT","edited_element_id":"certainty-2","old_element_id":"assertedValue","parameters":{"assertedValue":"electric oven"}}]}
```

The server logs the following (without problems):
```
web_1            | 2020-07-13 14:01:00,056 - INFO - consumers - Get request from user: 'jancho' with content: '{"method":"modify","payload":[{"element_type":"certainty","method":"PUT","edited_element_id":"certainty-2","old_element_id":"assertedValue","parameters":{"assertedValue":"electric oven"}}]}'
web_1            | 2020-07-13 14:01:00,186 - INFO - consumers - Content of file: 'group_0_long_annotated_2_modified_xml' updated with request from user: 'jancho' was sent to users: 'jancho'
web_1            | HTTP GET /close_reading/project/2/file/16/ 200 [0.04, 172.18.0.1:51016]
```

However the annotation still has the old value. The same happens with any other attribute or with complex 
requests such the following:
```
{"method":"modify","payload":[
{"element_type":"certainty","method":"PUT","edited_element_id":"certainty-2","old_element_id":"ana","parameters":{"ana":["ignorance"]}},
{"element_type":"certainty","method":"PUT","edited_element_id":"certainty-2","old_element_id":"cert","parameters":{"cert":"very high"}},
{"element_type":"certainty","method":"PUT","edited_element_id":"certainty-2","old_element_id":"assertedValue","parameters":{"assertedValue":"electric oven"}}]}
```

**Comment by bug-rancher** [comment]
Cause of this situation and walk-around is described in https://github.com/providedh/collaborative-platform/issues/111#issuecomment-659373035.

**Comment by Janchorizo** [comment]
If I understand it right, it is not possible to modify an unsaved property or certainty annotation?

**Comment by Janchorizo** [comment]
Moreover, I don't understand why an annotation would only be able to be modified after being saved.
Wouldn't the API work the same way? 
Please explain me why it works differently from properties (which are correctly modified) so that I can
understand your reasoning and implement the UI accordingly.

**Comment by bug-rancher** [comment]
On concept stage I assumed that user can:
- add a new element (tag/reference to entity/entity property/certainty) to a document
- modify EXISTING element in a document
- remove EXISTING element in a document

I assumed that the element exist in the document TO THE MOMENT, when user delete this element, and then SAVE file with confirmation, that he wanted to save the change.
Analogous, the element STARTS to exist in the document, when user add it, and then SAVE file with confirmation, that he wanted to save the change.
I assumed if user wants to remove the element that he DIDN'T SAVE previously, he needs to DISCARD the change, not delete the element.
So, from this point of view, possibility of editing/removing not saved elements is a bug.

As I described in #111, I need to consider if let users edit/delete unsaved changes or not and do this in one consistent way for all elements (tags/references/certainties etc.). Your point of view is correct. I'm aware of that there is now possibility to edit unsaved property. Maybe this incoherence is caused by my overlook, or maybe I needed to handle uncertainties in this way by some reason I can not recall.

Probably there is better way for users to handle operations on elements in a document, but I think this concept is correct and consistent. Comparing with previous version of Annotator, this version gives users more new possibilities. When we will start to use a new Annotator in real cases and we will see the change of paradigm I previously assumed will make some good change for users, we always can rewrite this.

**Comment by Janchorizo** [comment]
I don't see the difference in editing a saved or unsaved element to be honest. At least how I approach at editing tools
is by making and editing until I am satisfied and then saving (i.e.: I wouldn't expect Microsoft Paint to prevent me from
changing the fill color of a rectangle until I save that first draw of the rectangle).

In our case, I don't see the logic behind editing or removing saved elements as a user is most likely to not save something
he/she is not happy with. And don't see why he/she should redo a complete annotation just to fix the spelling of a field
before saving.

Do you think we can work towards this? I don't think this would be a big change and do think it is more consistent to allow
changing values before saving the changes.

**Comment by Janchorizo** [comment]
Just because unsaved elements do _exist_, it just that the user has not committed his/her changes (so we
should give the option to get to a desired value before saving).

**Comment by bug-rancher** [comment]
The issue is fixed. 

Now backend supports modifying all unsaved elements. Every modification of an unsaved element is treated as an update to the operation that created the element. E.g. if user add a certainty with parameter `"cert": "low"`, and then modify this unsaved certainty with parameter `"cert": "high"`, in response it will look like user has created certainty with parameter `"cert": "high"` at the beginning (there will not be a modifying operation in response, only creating operation).

**Comment by bug-rancher** [comment]
BTW, you have a bug in request. Instead of `assertedValue` should be `asserted_value`. Whole names in API are coded with `snake_case` style.
