### ISSUE TITLE
Pop-ups in annotator doesn't close on successful action completion

### ISSUE THREAD

**Issue by virdiignis** [providedh/collaborative-platform#134]
In Annotator, after e.g. creating new entity, the pop-up is still visible when annotation has been already made. I think, that final confirmation (click on Create button), should also close the pop-up. What are everyone's thoughts on this?

**Comment by Janchorizo** [comment]
I am yet to have the server respond to me after I send any message, when
running the platform over docker. Therefore, I didn't want to code anything
depending on the server response.

**Comment by Janchorizo** [comment]
I handle websockets messages by first checking if they fit the expected JSON schema. Therefore, having websockets work correctly in docker is important so that I can check the responses provided by the server; as almost always no response is provided.

Furthermore, this websocket API does not make distinctions between the result of _my (current user)_ and others' actions; therefore, I was reluctant to close a form if I can't confirm that it was received either correctly or erroneously.

**Comment by virdiignis** [comment]
As to your issues with docker: I discovered, that the websockets responses work for me after I reset the server, and go to the annotator via the link from file page. It stops working after the first page refresh. Maybe It's the same for you — hope this helps.
