### ISSUE TITLE
Replace the ab tag with the seg tag

### ISSUE THREAD

**Issue by michalkozak** [providedh/collaborative-platform#180]
Currently when we annotate uncertainty without entity we use the ab tag. Reviewers suggest using the seg tag as a purely stand-off form of annotation ("ab is a paragraph-like but without the semantics of a paragraph").

Let's change the tag in TEI.

**Comment by bug-rancher** [comment]
Hi @Janchorizo , I updated the handling `<ab>` tags to `<seg>` tags on backend. `xml:id` of this tags are changed accordingly from `xml:id="ab-X"` to `xml:id="seg-X"`. If this changes affect on frontend, please update frontend part.

**All changes are on `tei_format_updates` branch.**

**Comment by Janchorizo** [comment]
I am making changes on another branch. Do you want this change on `tei_format_updates` branch?

**Comment by bug-rancher** [comment]
I think fixing frontent part of this issue on this same branch will be better, because we will see if everything works fine before we merge changes to develop and deploy on test server. If I merge this branch to `develop` before frontend update, and if my changes cause some problems on frontend, this problems will be deployed to test server.

**Comment by Janchorizo** [comment]
The change is present in the `tei_format_updates`.
