### ISSUE TITLE
`start_pos` and `end_pos` are equal in request in Annotator

### ISSUE THREAD

**Issue by bug-rancher** [providedh/collaborative-platform#183]
If user select text fragment that have tags already (e.g. "Michollstowne" in fragment `...of <name xml:id="name-6" resp="#annotator-3" ref="#place-0"> Michollstowne</name> Barrony...`) and he want to add an uncertainty to this fragment, `start_pos` and `end_pos` in request are equal.

Link to the file: https://providedh-test.ehum.psnc.pl/close_reading/project/3/file/4/
Selected fragment: "Michollstowne" in second line of text

**Comment by Janchorizo** [comment]
I have tried to handle this but it won't work. Text selection seems to work form me every time in that same file.
However, because of how events are handled, just one of the two (say an entity and a text selection) just one will
show upon hover, and the icons and filling will overlap.

This is something that can not be handled in the current implementation.
