### ISSUE TITLE
In Annotator, after adding entity, interface disappear.

### ISSUE THREAD

**Issue by bug-rancher** [providedh/collaborative-platform#186]
As in subject.
On branch `tei_format_update`.
Sample files: https://drive.google.com/drive/folders/1PhsbbNRjq8nCBgHLRgq3xyA9PhsLugjw
Sample request:
```
{
    "method": "modify",
    "payload": [
        {
            "element_type": "tag",
            "method": "POST",
            "parameters": {
                "end_pos": 848,
                "start_pos": 844
            }
        },
        {
            "edited_element_id": 0,
            "element_type": "reference",
            "method": "POST",
            "parameters": {
                "entity_type": "person"
            }
        },
        {
            "edited_element_id": 1,
            "element_type": "entity_property",
            "method": "POST",
            "parameters": {
                "name": "aaaa"
            }
        }
    ]
}
```

**Comment by Janchorizo** [comment]
After annotating a piece of text, a name tag gets created with the following format:
`<name xml:id="seg-0" respAdded="#annotator-3" saved="false" refAdded="#object-0" xml:idAdded="name-7" xml:idDeleted="seg-0">Pint of Water</name>`

As you can see the `xml:id` property is _modified_ and the expected value the one stated as _added_. However:
- `xml:idDeleted` = 'seg-0' and `xml:idAdded` = 'name-7', so the newer value is 'name-7'.
- The tag type is a `<name>` tag so the newer `xml:id` value of 'name-7' would make sense.
- The actual tag's `xml:id` value is 'seg-0'.

Therefore, the app can't find it. I will fix the app crashing because of this bug but there is an issue in backend that must be fixed
in order for the name tags to work within the annotator.

**Comment by bug-rancher** [comment]
Format of `<name>` tag is correct. After adding a reference to element, `xml:id` of this element is still this same. This attribute will be modified only after saving file, according to attributes `xml:idAdded` and `xml:idDeleted`. This is expected behavior, backend work in this way from months and I wasn't change anything there during last modifications. Before change from `<ab>` to `<seg>` frontend wasn't have problems with this. This is not a backend issue.

**Comment by bug-rancher** [comment]
With your latest changes interface stop crushing, but after adding entity, annotated text don't have any underline or icon. Before this changes this underline and icon was visible just after adding a entity. Now they appear after file save.

**Comment by Janchorizo** [comment]
You were right. This issue appear because I changed it to the behavior described above as I thought that it was a bug.
It should be now fixed.
