### ISSUE TITLE
Add the xml:id attribute to certainty annotations.

### ISSUE THREAD

**Issue by Janchorizo** [providedh/collaborative-platform#6]
Add back-end code for adding ids to certainty tags Needed for
creating annotations based on previously done ones.

**Comment by michalkozak** [comment]
In this task we could add this `id` and `degree` attributes to GET methods returning annotations in JSON.

We have to extend API for annotating. It should take optional attribute annotationId if annotation concerns other annotation. This annotation can only concerns value of an attribute of the certainty element. So validations have to be implemented.

**Comment by Janchorizo** [comment]
I extended the API to allow annotations based on the xml:id attribute to reference already existing
elements in the document. Adding the ids to the annotations and checking that the locus and
attribute correspond to the referenced attributes would be sufficient.

**Comment by bug-rancher** [comment]
I modified Annotator code to add xml:id to certainties. Unfortunately changes are on `api-vis` branch instead 'feature-annotator-uncertainty-list' as we agreed with @Janchorizo, because we change way of calculating xml:id number some time ago (now the max number for each category is stored in database) and this changes are not reflected on 'feature-annotator-uncertainty-list' branch yet.
